development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://scotch.snstheatre.org/faye"
  secret_token: "cf84ff617622f0feee011735c8f2a336b412179eebb72ca997ff8ae4b6136e88"
  signature_expiration: 3600 # one hour
