class SeedItemCategories < ActiveRecord::Migration
  def self.up
    #Create ItemCategories from current SotW
    ItemCategory.transaction do
      p = ItemCategory.create(:prefix => 0, :name => "Office Equipment")
      ItemCategory.create(:prefix => 0, :name => "Electronics", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Finance", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Library and Archives", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "Furniture", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "Office Supplies", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Office", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 1, :name => "Carpentry")
      ItemCategory.create(:prefix => 0, :name => "Power Tools", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Non-Power Tools", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Flats", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "Doors", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "Platforms", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Carpentry", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 2, :name => "Paint")
      ItemCategory.create(:prefix => 0, :name => "Stage Paint", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Fence Paint", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Painting Equipment", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Paint", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 3, :name => "Sound")
      ItemCategory.create(:prefix => 1, :name => "Speakers/Stands", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Sound Board", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "Mic ELements", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "Mic Packs", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 5, :name => "Cables and Adapters", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 6, :name => "Clearcom", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Sound", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 4, :name => "Lighting")
      ItemCategory.create(:prefix => 0, :name => "Instruments", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Barrels", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Instrument Accessories", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "Lighting Consoles", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "Power/Electrics Capital", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 5, :name => "LC and DMX Cable", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 6, :name => "Trees and Bases", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 7, :name => "Gel Material", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 8, :name => "Lamps", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Lighting", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 5, :name => "Costumes")
      ItemCategory.create(:prefix => 0, :name => "Capital Equipment", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Classical", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Medieval", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "16th Century", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "17th Century", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 5, :name => "18th Century", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 6, :name => "19th Century", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 7, :name => "1900s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 8, :name => "1910s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 9, :name => "1920s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 10, :name => "1930s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 11, :name => "1940s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 12, :name => "1950s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 13, :name => "1960s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 14, :name => "1970s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 15, :name => "1980s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 16, :name => "1990s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 17, :name => "2000s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 18, :name => "2010s", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 19, :name => "Arabia", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 20, :name => "Sequined", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 21, :name => "Suits", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 96, :name => "Accessories", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 97, :name => "Pantomime/Animals", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 98, :name => "Uniforms", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Costumes", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 6, :name => "Props")
      ItemCategory.create(:prefix => 0, :name => "Bedroom", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Living Room", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Kitchen - Ceramics", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "Kitchen - Glassware", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "Kitchen - Cooking Supplies", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 5, :name => "Kitchen - Plasticware", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 6, :name => "Kitchen - Serving Items", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 7, :name => "Kitchen - Misc", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 8, :name => "Bathroom", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 9, :name => "Outdoors", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 10, :name => "Office Supplies", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 11, :name => "Toys", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 12, :name => "Practical", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 13, :name => "Accessories", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Props", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 7, :name => "Hair/Makeup")
      ItemCategory.create(:prefix => 99, :name => "Misc. Hair/Makeup", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 8, :name => "Mixed Use")
      ItemCategory.create(:prefix => 0, :name => "Dungeon Carts", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 1, :name => "Edison Extension Cords", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 2, :name => "Curtains", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 3, :name => "Cleaning Supplies", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 4, :name => "Storage Boxes", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Misc. Mixed Use", :parent_category_id => p.id)

      p = ItemCategory.create(:prefix => 9, :name => "Miscellaneous")
      ItemCategory.create(:prefix => 0, :name => "ABTech Shared Equipment", :parent_category_id => p.id)
      ItemCategory.create(:prefix => 99, :name => "Miscellaneous", :parent_category_id => p.id)
    end
  end

  def self.down
  end
end
